FROM python:3
# создание рабочей дирректории
WORKDIR /usr/src/app
# копирование requirements.txt в рабочую дирректорию
COPY requirements.txt ./
# устанавливаем requirements.txt (зависимости)
RUN pip install -r requirements.txt
